== CityGML概述

CityGML是一种基于XML格式的、用于存储和交换虚拟3D城市模型的开放数据模型。它是地理标记语言3.1.1版本(GML3)的一个应用模式，是由OGC和ISO TC211发布的用于空间数据交换的可扩展国际标准

开发CityGML的目标是为了对三维城市模型的基本实体、属性和关系达成一个共同的定义。这对于三维城市模型的低成本、可持续性维护尤其重要，因为其允许在不同的应用领域重复使用相同的数据。

CityGML不仅表现了城市模型的图形外观，而且特别解决了语义和主题属性、分类法和聚合的表示。CityGML包括一个几何图形模型和一个主题模型。CityGML包括一个几何模型和一个主题模型。几何模型允许对三维城市模型中的空间对象的几何和拓扑属性进行一致和同质的定义（第8章）。所有对象的基类是__ _CityObject__，它是GML的__ _Feature__类的一个子类。所有的对象都继承了__ _CityObject__的属性。

CityGML的主题模型采用了不同主题领域的几何模型，如数字地形模型、场地（即建筑物、桥梁和隧道）、植被（单独的对象以及区域和体积的生物群落）、土地利用、水体、交通设施和城市家具（第10章）。更多尚未明确建模的对象，可以使用通用对象和属性的概念来表示（第6.11章）。此外，对CityGML数据模型的扩展，适用于特定的应用领域，可以使用应用域扩展（ADE）来实现（第6.12章）。相同形状的空间对象，如树等，在不同的位置出现多次，也可以被建模为原型，并在城市模型中多次使用(第8.2章)。分组的概念可以将单个三维物体组合起来，例如将建筑物组合成一个建筑群（6.8章）。没有用封闭实体进行几何建模的对象，可以使用__ClosureSurfaces__封闭(第6.4章)被虚拟密封，以计算其体积（例如人行地下通道、隧道或飞机库）。__TerrainIntersectionCurve__的概念被引入，将三维物体与数字地形模型的正确位置结合起来，以防止建筑物漂浮或沉入地形（6.5章）。

CityGML区分了五个连续的细节层次模型(LOD)，对象的几何图形和主题差异随着LOD的增加而变得更加详细(第6.2章)。CityGML文件可以-但不是必须-同时为不同LOD中的每个对象包含多种表示(和几何图形)。泛化关系允许在不同尺度上明确表示聚合对象。

除了空间属性之外，CityGML的特征还可以被赋予外观。外观并不局限于视觉数据，而是代表地物表面的任意可观察的属性，如红外辐射、噪声污染或地震引起的结构应力（第9章）。

此外，对象可以是对外部数据集中相应对象的外部引用（第6.7章）。枚举型对象属性的可能属性值，可以在外部可重新定义的字典中定义的代码列表中枚举（第6.6章）。
